# Generated by Django 5.1.4 on 2026-02-15 00:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(help_text="Driver's current location (address or city, state)", max_length=255)),
                ('pickup_location', models.CharField(help_text='Pickup location (address or city, state)', max_length=255)),
                ('dropoff_location', models.CharField(help_text='Dropoff/delivery location (address or city, state)', max_length=255)),
                ('current_cycle_used', models.FloatField(default=0.0, help_text='Hours already used in the current 70hr/8day cycle')),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lng', models.FloatField(blank=True, null=True)),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_lng', models.FloatField(blank=True, null=True)),
                ('total_distance_miles', models.FloatField(blank=True, help_text='Total trip distance in miles', null=True)),
                ('total_duration_hours', models.FloatField(blank=True, help_text='Total estimated driving duration in hours', null=True)),
                ('total_trip_days', models.IntegerField(blank=True, help_text='Total number of days the trip will span', null=True)),
                ('route_geometry', models.JSONField(blank=True, help_text='Route coordinates for map display [[lat, lng], ...]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('start', 'Trip Start'), ('fuel', 'Fuel Stop'), ('rest', 'Rest Break (30 min)'), ('sleep', 'Sleep/Off-Duty (10 hr)'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=20)),
                ('location_name', models.CharField(help_text='City/address name of the stop', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('miles_from_start', models.FloatField(default=0.0, help_text='Cumulative miles from trip start')),
                ('hours_from_start', models.FloatField(default=0.0, help_text='Cumulative driving hours from trip start')),
                ('stop_duration_hours', models.FloatField(default=0.0, help_text='How long the driver stops here (hours)')),
                ('sequence_order', models.IntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trip_planner.trip')),
            ],
            options={
                'verbose_name': 'Trip Stop',
                'verbose_name_plural': 'Trip Stops',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='Day number in the trip (1-indexed)')),
                ('date', models.DateField(help_text='Calendar date for this log')),
                ('off_duty_hours', models.FloatField(default=0.0)),
                ('sleeper_berth_hours', models.FloatField(default=0.0)),
                ('driving_hours', models.FloatField(default=0.0)),
                ('on_duty_hours', models.FloatField(default=0.0)),
                ('total_miles_today', models.FloatField(default=0.0)),
                ('duty_status_entries', models.JSONField(default=list, help_text='Timeline of duty status changes for drawing the ELD grid')),
                ('remarks', models.JSONField(default=list, help_text='List of remarks: [{location, activity, time}]')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trip_planner.trip')),
            ],
            options={
                'verbose_name': 'Daily Log',
                'verbose_name_plural': 'Daily Logs',
                'ordering': ['day_number'],
                'unique_together': {('trip', 'day_number')},
            },
        ),
    ]
