# Generated by Django 5.1.4 on 2026-02-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cycle_hours_after_trip',
            field=models.FloatField(blank=True, help_text='Cycle hours used after trip completion (accounts for 34-hr restart)', null=True),
        ),
    ]
